[package]
name = "hubtools"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.version = "1"
toml.version = "0.7"
srec.version = "0.2.0"
zip.version = "0.5.13"
zerocopy.version = "0.6"
path-slash.version = "0.1"
