[package]
name = "hubtools"
version = "0.1.0"
edition = "2021"

[dependencies]
path-slash.version = "0.1"
srec.version = "0.2.0"
tempfile.version = "3"
thiserror.version = "1"
toml.version = "0.7"
zerocopy.version = "0.6"
zip.version = "0.5.13"
