[package]
name = "hubtools"
version = "0.1.0"
edition = "2021"

[dependencies]
object = { version = "0.30", default-features = false, features = ["write", "read"] }
path-slash = "0.1"
thiserror = "1"
toml = "0.7"
zerocopy = "0.6"
zip = "0.6"

tlvc.git = "https://github.com/oxidecomputer/tlvc"
tlvc-text.git = "https://github.com/oxidecomputer/tlvc"
