[package]
name = "hubtools"
version = "0.1.0"
edition = "2021"

[dependencies]
ihex = "3.0"
object = { version = "0.30", default-features = false, features = ["write"] }
path-slash = "0.1"
srec = "0.2.0"
tempfile = "3"
thiserror = "1"
toml = "0.7"
zerocopy = "0.6"
zip = "0.5.13"

tlvc.git = "https://github.com/oxidecomputer/tlvc"
tlvc-text.git = "https://github.com/oxidecomputer/tlvc"
