[package]
name = "hubtools"
version = "0.4.8"
edition = "2024"

[dependencies]
digest.workspace = true
hex.workspace = true
lpc55_areas.workspace = true
lpc55_sign.workspace = true
object.workspace = true
path-slash.workspace = true
rsa.workspace = true
thiserror.workspace = true
tlvc-text.workspace = true
tlvc.workspace = true
toml.workspace = true
x509-cert.workspace = true
zerocopy.workspace = true
zip.workspace = true
